name: Optimize Code (roundup)
on:
  workflow_dispatch:
  # push:
  #   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest      # Docker-based github actions have to run on a linux environment
    env:
        prepo: ${{github.repository}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Minify Actions
        uses: amireshoon/minifyAction@main
        with:
          repo: $prepo
      - name: Minifying Codes
        run: |
          minifier.sh $prepo
      - name: Pushing to production branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          directory: github/workspace
          branch: production
          message: Minified css, js and html
          author_name: MinifyAction[bot]
          author_email: amireshoon-minifyAction@users.noreply.github.com
          force: true