on:
  push:
    branches: [main]
jobs:
  deploy_sftp_job:
    name: Flywheel SFTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ssh.getflywheel.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v3
      # with:
      #   path : 'temp-dir'
      #   sparse-checkout: |
      #     roundup
    - name: Copy files over to flywheel server for freelegalreviews.com
      run: rsync -rauvhP /home/runner/work/FLR-roundup/FLR-roundup/* anovadigital+freelegalreviews@ssh.getflywheel.com:/www/github-cicd --rsh "ssh -p 22 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --recursive -rltgoDzvO --exclude .git --exclude .github --exclude README.md
    - name: Clean up .ssh directory
      run: rm -rf ~/.ssh