on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  deploy_sftp_job:
    name: Flywheel SSH Deploy
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ssh.getflywheel.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v3
      with:
        path : 'tmp-directory'
        sparse-checkout: .
    - name: list temp directory
      run: cd /home/runner/work/FLR-roundup/FLR-roundup/tmp-directory && ls
    - name: copy files to remote server
      run: rsync /home/runner/work/FLR-roundup/FLR-roundup/tmp-directory anovadigital+freelegalreviews@ssh.getflywheel.com:/www/github-cicd --rsh "ssh -p 22 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --recursive -rltgoDzvO --exclude .git --exclude .github -P
    - name: cleanup
      run: rm -rf ~/.ssh